### ISSUE TITLE
Load photos , from Google Photo

### ISSUE THREAD

**Issue by DaniyarAmangeldy** [ParkSangGwon/TedBottomPicker#27]
Selecting local images works ok, but when I select some image not from file:// , but content:// , it crashes

**Comment by ParkSangGwon** [comment]
What is your library version?
Let me know.

**Comment by DaniyarAmangeldy** [comment]
1.0.8 Version

**Comment by DaniyarAmangeldy** [comment]
It happens , because image is not in external storage.. And when your ActivityResult tries find file in external storage by Uri.getPath(); it crashes. Need to download image from google photo first, then set it. :)

**Comment by ParkSangGwon** [comment]
@DaniyarAmangeldy 
Hm... I can not understand exactly.
Can you explain with error log?

**Comment by DaniyarAmangeldy** [comment]
You can see this problem from StackOverFlow.

**Comment by DaniyarAmangeldy** [comment]
You can see this problem

**Comment by prophet173** [comment]
from above solution link... you can turn bitmap into uri, which will result in saving picture in Pictures directory... in short, here`s workaround:
```
if (temp.toString().startsWith("content://com.google.android.apps.photos.content")){
            try {
                InputStream is = getActivity().getContentResolver().openInputStream(temp);
                if (is != null) {
                    Bitmap pictureBitmap = BitmapFactory.decodeStream(is);
                    String realPath = RealPathUtil.getRealPath(getActivity(), getImageUri(getActivity(), pictureBitmap));
                    Uri selectedImageUri = Uri.fromFile(new File(realPath));
                    complete(selectedImageUri);
                }
            } catch (FileNotFoundException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        } else {
            String realPath = RealPathUtil.getRealPath(getActivity(), temp);
            Uri selectedImageUri = Uri.fromFile(new File(realPath));
            complete(selectedImageUri);
        }

public Uri getImageUri(Context inContext, Bitmap inImage) {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        inImage.compress(Bitmap.CompressFormat.JPEG, 100, bytes);
        String path = MediaStore.Images.Media.insertImage(inContext.getContentResolver(), inImage, "img", null);
        return Uri.parse(path);
    }
```

**Comment by prophet173** [comment]
From above solution link, here`s my workaround:

```
    private void onActivityResultGallery(Intent data) {
        Uri temp = data.getData();

        if (temp == null) {
            errorMessage();
        }

        if (temp.toString().startsWith("content://com.google.android.apps.photos.content")){
            try {
                InputStream is = getActivity().getContentResolver().openInputStream(temp);
                if (is != null) {
                    Bitmap pictureBitmap = BitmapFactory.decodeStream(is);
                    String realPath = RealPathUtil.getRealPath(getActivity(), getImageUri(getActivity(), pictureBitmap));
                    Uri selectedImageUri = Uri.fromFile(new File(realPath));
                    complete(selectedImageUri);
                }
            } catch (FileNotFoundException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        } else {
            String realPath = RealPathUtil.getRealPath(getActivity(), temp);
            Uri selectedImageUri = Uri.fromFile(new File(realPath));
            complete(selectedImageUri);
        }

    }

    public Uri getImageUri(Context context, Bitmap bitmap) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 100, baos);
        String path = MediaStore.Images.Media.insertImage(context.getContentResolver(), bitmap, "img", null);
        return Uri.parse(path);
    }
```

**Comment by ParkSangGwon** [comment]
@DaniyarAmangeldy I think that is not library's problem.
Show me your source code.
Thanks you @prophet173

**Comment by DaniyarAmangeldy** [comment]
@OnClick(R.id.rv_item_create_icon_camera)
        public void setPhoto(){
            new TedBottomPicker.Builder(context)
                    .showTitle(false)
                    .setSelectMaxCount(20 - images.size())
                    .setOnMultiImageSelectedListener(this)
                    .setCompleteButtonText(R.string.string_done)
                    .setSelectMaxCountErrorText(R.string.string_max_photo)
                    .create()
                    .show(manager);

        }

        @Override
        public void onImagesSelected(ArrayList<Uri> uriList) {
            for(Uri uri: uriList){
                images.add(uri.getPath());
            }
            notifyDataSetChanged();
            ((acCreateApartment) context).setApartmentPhotos(images);
        }

**Comment by gtcompscientist** [comment]
This was fixed in Pull #29

**Comment by StephenMilone** [comment]
I'm still having this crash happen on 1.0.12.

From bottom sheet, tap gallery, which loads google photos, select a photo not on the device, see the google photos downloading dialog, then crash.

Let me know if you need more info, the stack trace points here:

Caused by: java.lang.NullPointerException: uriString
                                                                            at android.net.Uri$StringUri.<init>(Uri.java:475)
                                                                            at android.net.Uri$StringUri.<init>(Uri.java)
                                                                            at android.net.Uri.parse(Uri.java:437)
                                                                            at gun0912.tedbottompicker.TedBottomPicker.onActivityResultGallery(TedBottomPicker.java:566)

**Comment by paramvir-singh88** [comment]
Is this issue resolved? I am getting crash if attempt to select photo is made.

**Comment by ursrudra** [comment]
me too having the same issue, unable to select photo from gallery and camera

**Comment by anurags2102** [comment]
Hi,

I am doing deeplinking in my app. So I've opened google photos and by tap on share icon, opening my app and sending image path. I am getting following path in intent:

content://com.google.android.apps.photos.contentprovider/0/1/mediakey:/local%253A02ae48d5-e576-449b-994f-1db260da79c0/REQUIRE_ORIGINAL/NONE/2022132799

When I have tried your code its crashing and not getting actual path to download image. Please tell me what I am doing wrong.
